version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING.JPA.PROPERTIES.HIBERNATE.JDBC.LOB.NON_CONTEXTUAL_CREATION=true
      - SPRING.JPA.PROPERTIES.HIBERNATE.JDBC.BATCH_SIZE=25

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres